tests: 
- actions: # list of actions to validate
  - iam:Group*
  - iam:Policy*
  - iam:Role*
  - lambda:Function*
  - cloudformation:CustomResource*
  - sns:Topic*  
  - sns:TopicPolicy*
  - sns:Policy*  
  expected_result: succeed
  resources: 
  - "*"
global_limit_to: # These roles and/or users below will be u. Regular expressions are supported
- "^arn:aws:iam::(\\d{12}):user/(.*)({account_id})(.*)$"